name: Customer Portal Hybrid CI/CD Pipeline
 
on:
  push:
    branches:
      - main
 
jobs:
 
  # -------------------------------
  # 1. BUILD STAGE (GitHub Hosted)
  # -------------------------------
  build:
    name: Build Application
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Validate PHP Syntax
        run: |
          find src -name "*.php" -exec php -l {} \;
 
      - name: Build Completed
        run: echo "Build successful"
 
  # -----------------------------------
  # 2. DATABASE DEPLOY (Self Hosted)
  # -----------------------------------
  deploy-db:
    name: Deploy Database Changes
    runs-on: self-hosted
    needs: build
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Run SQL Script (Insert Data)
        run: |
          /opt/mssql-tools/bin/sqlcmd \
          -S ${{ secrets.DB_SERVER }} \
          -d ${{ secrets.DB_NAME }} \
          -U ${{ secrets.DB_USER }} \
          -P ${{ secrets.DB_PASSWORD }} \
          -i database/insert_data.sql
 
  # -----------------------------------
  # 3. VERIFY DATA
  # -----------------------------------
  verify-db:
    name: Verify Database Changes
    runs-on: self-hosted
    needs: deploy-db
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Verify Inserted Data
        run: |
          /opt/mssql-tools/bin/sqlcmd \
          -S ${{ secrets.DB_SERVER }} \
          -d ${{ secrets.DB_NAME }} \
          -U ${{ secrets.DB_USER }} \
          -P ${{ secrets.DB_PASSWORD }} \
          -Q "SELECT * FROM [dbo].[DevOps_1]"
 
  # -----------------------------------
  # 4. ROLLBACK (ONLY IF FAILURE)
  # -----------------------------------
  rollback:
    name: Rollback on Failure
    runs-on: self-hosted
    needs: deploy-db
    if: failure()
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Run Rollback Script
        run: |
          /opt/mssql-tools/bin/sqlcmd \
          -S ${{ secrets.DB_SERVER }} \
          -d ${{ secrets.DB_NAME }} \
          -U ${{ secrets.DB_USER }} \
          -P ${{ secrets.DB_PASSWORD }} \
          -i database/rollback.sql
